<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;

/** Durable deletion intents: database commit first, unreferenced physical files second. */
class TaskAttachmentCleanup
{
    public function path(mixed $url): ?string
    {
        if (! is_string($url)) return null;
        $parts = parse_url($url);
        if ($parts === false || isset($parts['fragment']) || isset($parts['user']) || isset($parts['pass'])) return null;
        if (isset($parts['host']) || isset($parts['scheme'])) {
            $origin = parse_url(config('app.url'));
            foreach (['scheme', 'host', 'port'] as $key) {
                if (($parts[$key] ?? null) !== ($origin[$key] ?? null)) return null;
            }
        }
        $route = $parts['path'] ?? '';
        if ($route === '/api/chat-attachment') {
            parse_str($parts['query'] ?? '', $query);
            $name = $query['file'] ?? null;
        } elseif (preg_match('~\A/(?:storage/chat-attachments|api/chat-attachments)/([^/]+)\z~', $route, $match)) {
            $name = rawurldecode($match[1]);
        } else return null;
        // Only names generated by this application's uploader/externalization migration.
        if (! is_string($name) || ! preg_match('/\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.[a-z0-9]{0,218}\z/i', $name)) return null;
        return 'chat-attachments/'.$name;
    }

    /** Must be called inside the transaction deleting the task. */
    public function enqueue(array $attachments): array
    {
        $paths = [];
        foreach ($attachments as $attachment) {
            $path = $this->path($attachment['data'] ?? null);
            if (! $path) continue; // Inline base64 data disappears with the task row.
            DB::table('task_attachment_deletions')->insertOrIgnore(['id' => (string) Str::uuid(), 'path' => $path,
                'created_at' => now(), 'updated_at' => now()]);
            $paths[] = $path;
        }
        return array_values(array_unique($paths));
    }

    private function referenced(string $path): bool
    {
        $name = basename($path);
        // Scan bounded chunks, including legacy URL encodings and plain-text references.
        // A conservative filename match can preserve an extra file, never delete a shared one.
        foreach (['tasks' => ['attachments', 'description'], 'messages' => ['attachments', 'text', 'voice'],
            'users' => ['image'], 'projects' => ['description'], 'activities' => ['text'], 'notifications' => ['text']] as $table => $fields) {
            $found = false;
            DB::table($table)->select(array_merge(['id'], $fields))->chunkById(10, function ($rows) use ($name, &$found) {
                foreach ($rows as $row) {
                    foreach ((array) $row as $value) {
                        $decoded = is_string($value) ? json_decode($value, true) : null;
                        $search = is_array($decoded) ? json_encode($decoded, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) : $value;
                        if (is_string($search) && str_contains(strtolower(rawurldecode($search)), strtolower($name))) {
                            $found = true;
                            return false;
                        }
                    }
                }
            });
            if ($found) return true;
        }
        return false;
    }

    public function drain(?array $paths = null): void
    {
        $query = DB::table('task_attachment_deletions')->select('id', 'path');
        if ($paths !== null) $query->whereIn('path', $paths);
        $query->chunkById(100, function ($rows) {
            foreach ($rows as $row) {
                try {
                    app(StateConcurrency::class)->run(function () use ($row) {
                        if (! DB::table('task_attachment_deletions')->where('id', $row->id)->lockForUpdate()->exists()) return;
                        if ($this->path('/storage/'.$row->path) !== $row->path) throw new RuntimeException('Invalid cleanup path', 100);
                        if (! $this->referenced($row->path)) $this->deleteFile($row->path);
                        DB::table('task_attachment_deletions')->where('id', $row->id)->delete();
                    });
                } catch (\Throwable $exception) {
                    Log::warning('Task attachment cleanup deferred.', ['cleanup_id' => $row->id, 'error_type' => $exception::class, 'error_code' => $exception->getCode()]);
                }
            }
        });
    }

    protected function deleteFile(string $path): void
    {
        $disk = Storage::disk('public');
        $root = realpath($disk->path(''));
        $directory = $disk->path('chat-attachments');
        $target = $disk->path($path);
        if (! $root || is_link($directory) || is_link($target)) throw new RuntimeException('Unsafe attachment storage path', 101);
        if (! file_exists($target)) return; // Retry after unlink succeeded but queue acknowledgement failed.
        $expectedDirectory = $root.DIRECTORY_SEPARATOR.'chat-attachments';
        if (realpath($directory) !== $expectedDirectory || realpath($target) !== $expectedDirectory.DIRECTORY_SEPARATOR.basename($path) || ! is_file($target)) {
            throw new RuntimeException('Attachment lies outside managed storage', 102);
        }
        if (! $disk->delete($path)) throw new RuntimeException('Attachment deletion failed', 103);
    }
}
